car_come_domain:
  prod: https://ipark.keytop.cn/nkc/carCome/findCarComePage
  test: https://ipark-test.keytop.cn/nkc/carCome/findCarComePage
cloud_channel_change_url:
  prod: https://park.keytop.cn/kos_visitor/service/nodeController/changeNodeStatus
  test: https://ts.keytop.cn/kos_visitor/service/nodeController/changeNodeStatus
cloud_channel_query_url:
  prod: https://park.keytop.cn/kos_visitor/service/nodeController/queryNodeList
  test: https://ts.keytop.cn/kos_visitor/service/nodeController/queryNodeList
device:
  prod: &id001
    in_device: 192.168.24.117
    out_device: 192.168.24.118
  test: &id002
    in_device: 192.168.24.115
    out_device: 192.168.24.116
parking_lots:
  prod:
  - channel_names:
      192.168.24.117: sy入口117
      192.168.24.118: sy出口118
    description: '1234'
    devices: *id001
    id: '280030477'
    log_monitor:
      enabled: true
      log_directory: /home/keytop/log/ktparkcharge
      ssh_password: kt123456
      ssh_port: 22
      ssh_user: keytop
    name: 成都灰度环境封闭测试车场
    server_ip: 192.168.0.236
  test:
  - channel_names:
      192.168.24.115: sy入口115
      192.168.24.116: sy出口116
    description: '1234'
    devices: *id002
    id: '280025535'
    log_monitor:
      enabled: true
      log_directory: /home/keytop/log/ktparkcharge
      ssh_password: Kt_chengdu#123
      ssh_port: 10022
      ssh_user: root
    name: 天府新谷测试环境车场1
    server_ip: 192.168.0.183
support_parking_ips:
  prod:
  - '280030477'
  test:
  - '280025535'
support_server_ips:
  prod:
  - 192.168.0.236
  test:
  - 192.168.0.183
unity_login_domain:
  prod: http://park.keytop.cn
  test: https://ts.keytop.cn
yongce_pro:
  domain:
    prod: https://yongce-zshjcs.keytop.cn
    test: https://yongce-pro-test.keytop.cn
  top_group_id:
    prod: 38f188755bca474b896bb7e390589c40
    test: 92b9cc14ba134fc4a0fe74cbf4ef5af2
yongce_pro_domain:
  prod: http://ipark.keytop.cn/
  test: https://s2-test.keytop.cn/
